### ISSUE TITLE
Võtmete hoidmine HSM-ga

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/eIDAS-Client#1]
RIA infra (Tarmo) soovitus:
Võtmehoidla SAML vastuste allkirjastamiseks vajalikke võtmeid hoitakse võtmehoidlates (pkcs12, jks). // Kas HSM tugi on vajalik? Lisab keerukust. -- Lähtume, et ei ole. //

Minu meelest täiendavat keerukust ei teki kui teha asju nö. koosvõimeliselt. -  Ma soovitaks korra Paljakuga rääkida - pmt. me peaks tagama seda, et võtmehoidla lahenduks standardse moel nt. pkcs11 kaudu peaks iga vähegi taiplik masin olema võimeline kõhu all räääkima nii softwalletis oleva võtmega, aga ka nt. smartcardil olevaga ja kindlasti ka hsm'is olevaga.

**Comment by alarkvell** [comment]
HSM tugi lisatud v1.1.8 versioonis.
